# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Krikamol Muandet
email: krikamol@gmail.com
work_email: krikamol@tuebingen.mpg.de
work_place: "Max Planck Institute for Intelligent Systems"
work_address: "Max-Planck-Ring 4, 72076 Tübingen, Germany"
phone: +49 (0)7071 601 559
fax: +49 (0)7071 601 552
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Krikamol Muandet
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - bio.md
  - research.md
  - publication.md
  - teaching.md
  - tutorial.md

# generate social links in footer
social_links:
  twitter: krikamol
  github:  krikamol
  scholar: E2z5uYsAAAAJ
  dblp: Muandet:Krikamol
  researchgate: Krikamol_Muandet
  orcid: 0000-0002-4182-5282
  youtube_channel: UCBNUb-rZLKIJt2dTWkX-IDQ

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/pdf"
      pdf: true

collections:
  publications:
    paper: true
    output: true
    permalink: /:collection/:title

gems:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true

# essential files
krik_img_file: assets/img/krikamol.jpg
cv_file: assets/pdf/krikamol-cv.pdf
rs_file: assets/pdf/krikamol-research.pdf
pcr_file: assets/pdf/krikamol-pcr-research.pdf

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
